# Generated by Django 3.2 on 2023-07-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimineto',
            new_name='fecha_nacimiento',
        ),
    ]
